usePCC = true;
LABELS = {'Left Visual Cortex'; ...
          'Right Visual Cortex'; ...
          'Left Occipital Lobe'; ...
          'Right Occipital Lobe'; ...
          'Left Somatosensory Cortex'; ...
          'Right Somatosensory Cortex'; ...
          'Left Temporal Lobe'; ...
          'Right Temporal Lobe'; ...
          'Right Parietal Lobe'; ...
          'Left Motor Cortex'; ...
          'Left Parietal Lobe'; ...
          'Right Parietal Lobe'; ...
          'Left Occipital Lobe'; ...
          'Right Occipital Lobe'; ...
          'Left Parietal Lobe'; ...
          'Left Temporal Lobe'; ...
          'Right Temporal Lobe'; ...
          'Left Motor Cortex'; ...
          'Right Motor Cortex'; ...
          'Right Parietal Lobe'; ...
          'Right Parietal Lobe'; ...
          'Left Parietal Lobe'; ...
          'Right Parietal Lobe'; ...
          'Left Frontal Lobe'; ...
          'Right Frontal Lobe'; ...
          'Left Visual Cortex'; ...
          'Right Visual Cortex'; ...
          'Left Frontal Lobe'; ...
          'Right Frontal Lobe'; ...
          'Right Frontal Lobe'; ...
          'Left Frontal Lobe'; ...
          'Left Frontal Lobe'; ...
          'Right Frontal Lobe'; ...
          'Left Temporal Lobe'; ...
          'Right Temporal Lobe'; ...
          'Left Frontal Lobe'; ...
          'Right Frontal Lobe'; ...
          'Posterior Cingulate'; ... % only with PCC included
          'Medial Frontal Regions'};
      
NEW_ORDER = [32 36 31 24 28 5 10 18 11 15 22 1 26 3 13 34 7 16 ...
             17 8 35 14 4 27 2 20 23 21 9 12 19 6 29 30 25 33 37 38 39];

if ~usePCC, 
    LABELS(38) = [];
    NEW_ORDER(end) = [];
end
assert(length(NEW_ORDER) == length(LABELS));
          
          

